name: build
on: [ push, pull_request, workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version: [ 32, 30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10 ]
    container:
      image: perldocker/perl-tester:5.${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: perl-actions/install-with-cpanm@v1
        with:
          sudo: false
      - run: |-
          cd tools
          cpanm \
            --from https://cpan.metacpan.org/ --notest --force --skip-satisfied \
            --with-develop --with-all-features --installdeps .
          cpanm \
            --from https://cpan.metacpan.org/ --notest --force --skip-satisfied \
            Devel::Cover::Report::Codecov
          cd ..
      - run: HARNESS_PERL_SWITCHES=-MDevel::Cover prove --recurse --lib --failures --jobs 4 --timer tools/t
      - run: cover -report codecov
        if: ${{ matrix.perl-version >= 26 }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
