name: build
on:
  push:
    branches: [ master, integration ]
  pull_request:
    branches: [ master, integration ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:5.32
    steps:
      - uses: actions/checkout@v2
      - uses: perl-actions/install-with-cpanm@v1
        with:
          sudo: false
      - run: apt-get --yes --force-yes install wkhtmltopdf
      - run: |-
          cpanm --from https://cpan.metacpan.org/ --notest --force --skip-satisfied \
            --with-develop --with-all-features --installdeps . Devel::Cover::Report::Codecov
      - run: ./bin/build.pl -c
      - run: |-
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto-built PDFs for distribution"
          git push
